"""empty message

Revision ID: 1019b229de75
Revises: c6567a2762b2
Create Date: 2023-09-07 22:03:49.618155

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1019b229de75'
down_revision: Union[str, None] = 'c6567a2762b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('alert_notifications', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'alert_notifications')
    # ### end Alembic commands ###
