"""empty message

Revision ID: c6567a2762b2
Revises: 3c0669346b07
Create Date: 2023-09-02 05:22:46.023712

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c6567a2762b2'
down_revision: Union[str, None] = '3c0669346b07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
